"""add position cols to context nodes

Revision ID: 01bd71a33747
Revises: a3b0e571a39c
Create Date: 2025-08-15 20:13:15.333353

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01bd71a33747'
down_revision: Union[str, Sequence[str], None] = 'a3b0e571a39c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_nodes', sa.Column('pos_x', sa.Float(), nullable=False, server_default=sa.text("0.0")))
    op.add_column('context_nodes', sa.Column('pos_y', sa.Float(), nullable=False, server_default=sa.text("0.0")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_nodes', 'pos_y')
    op.drop_column('context_nodes', 'pos_x')
    # ### end Alembic commands ###
