"""add vectors table

Revision ID: 04cff13a6b12
Revises: b73335445677
Create Date: 2025-08-07 22:30:11.876905

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04cff13a6b12'
down_revision: Union[str, Sequence[str], None] = 'b73335445677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('vector_data', postgresql.ARRAY(sa.FLOAT()), nullable=False),
    sa.Column('vectorable_id', sa.Uuid(), nullable=False),
    sa.Column('vectorable_type', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectors_id'), 'vectors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vectors_id'), table_name='vectors')
    op.drop_table('vectors')
    # ### end Alembic commands ###
