"""add user_id to integrations

Revision ID: 3487afe1fe32
Revises: 0ab3c17d253b
Create Date: 2025-08-13 11:37:26.240971

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3487afe1fe32'
down_revision: Union[str, Sequence[str], None] = '0ab3c17d253b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('integrations', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_integrations_name'), table_name='integrations')
    op.create_index(op.f('ix_integrations_name'), 'integrations', ['name'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.create_index('uq_integrations_user_name', 'integrations', ['user_id', 'name'], unique=True)
    op.create_foreign_key(None, 'integrations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.drop_index('uq_integrations_user_name', table_name='integrations')
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_name'), table_name='integrations')
    op.create_index(op.f('ix_integrations_name'), 'integrations', ['name'], unique=True)
    op.drop_column('integrations', 'user_id')
    # ### end Alembic commands ###
