"""update chunks table

Revision ID: 43300531862a
Revises: 0d87a2d628be
Create Date: 2025-08-09 21:32:16.673554

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '43300531862a'
down_revision: Union[str, Sequence[str], None] = '0d87a2d628be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('content_ctx', sa.Text(), nullable=False))
    op.add_column('chunks', sa.Column('embedding_ctx', pgvector.sqlalchemy.vector.VECTOR(), nullable=False))
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=False))
    op.drop_column('chunks', 'embedding_ctx')
    op.drop_column('chunks', 'content_ctx')
    # ### end Alembic commands ###
