"""add settings column to user model

Revision ID: a3b0e571a39c
Revises: c7dd0e9b5d3e
Create Date: 2025-08-13 18:32:46.706150

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3b0e571a39c'
down_revision: Union[str, Sequence[str], None] = 'c7dd0e9b5d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'settings',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
