"""update context nodes

Revision ID: a842e4b9f39f
Revises: f073773041b4
Create Date: 2025-07-31 20:45:30.342699

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a842e4b9f39f'
down_revision: Union[str, Sequence[str], None] = 'f073773041b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_nodes', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('context_nodes', sa.Column('type', sa.VARCHAR(length=255), nullable=False))
    op.alter_column('context_nodes', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('context_nodes', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_context_nodes_status'), 'context_nodes', ['status'], unique=False)
    op.create_index(op.f('ix_context_nodes_type'), 'context_nodes', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_nodes_type'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_status'), table_name='context_nodes')
    op.alter_column('context_nodes', 'source',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('context_nodes', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('context_nodes', 'type')
    op.drop_column('context_nodes', 'content')
    # ### end Alembic commands ###
