"""add pgvector

Revision ID: b73335445677
Revises: e1b01cf17c8c
Create Date: 2025-08-07 22:09:45.508048

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b73335445677'
down_revision: Union[str, Sequence[str], None] = 'e1b01cf17c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP EXTENSION IF EXISTS vector")
