"""create context nodes

Revision ID: f073773041b4
Revises: d0ae9f60fa03
Create Date: 2025-07-06 23:38:51.942655

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f073773041b4'
down_revision: Union[str, Sequence[str], None] = 'd0ae9f60fa03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(255), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('status', sa.String(255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_nodes_external_id'), 'context_nodes', ['external_id'], unique=False)
    op.create_index(op.f('ix_context_nodes_id'), 'context_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_context_nodes_link'), 'context_nodes', ['link'], unique=False)
    op.create_index(op.f('ix_context_nodes_name'), 'context_nodes', ['name'], unique=False)
    op.create_index(op.f('ix_context_nodes_source'), 'context_nodes', ['source'], unique=False)
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_index(op.f('ix_context_nodes_source'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_name'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_link'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_id'), table_name='context_nodes')
    op.drop_index(op.f('ix_context_nodes_external_id'), table_name='context_nodes')
    op.drop_table('context_nodes')
    # ### end Alembic commands ###
