"""add episode_uuids to context nodes

Revision ID: f42c9860b0b6
Revises: a842e4b9f39f
Create Date: 2025-07-31 23:24:39.350580

"""
# pylint: disable=no-member, line-too-long
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f42c9860b0b6'
down_revision: Union[str, Sequence[str], None] = 'a842e4b9f39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_nodes', sa.Column('episode_uuids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context_nodes', 'episode_uuids')
    # ### end Alembic commands ###
